name: 'jira'
version: '0.1.0'
config-version: 2
require-dbt-version: [">=0.18.0", "<0.19.0"]


vars:

  jira:
    issue: "{{ ref('stg_jira__issue') }}"
    project: "{{ ref('stg_jira__project') }}"
    board: "{{ ref('stg_jira__board') }}"
    user: "{{ ref('stg_jira__user') }}"
    issue_type: "{{ ref('stg_jira__issue_type') }}"
    status: "{{ ref('stg_jira__status') }}"
    resolution: "{{ ref('stg_jira__resolution') }}"
    priority: "{{ ref('stg_jira__priority') }}"
    issue_multiselect_history: "{{ ref('stg_jira__issue_multiselect_history') }}"
    issue_field_history: "{{ ref('stg_jira__issue_field_history') }}"
    comment: "{{ ref('stg_jira__comment') }}"
    issue_link: "{{ ref('stg_jira__issue_link') }}"
    component: "{{ ref('stg_jira__component') }}"
    field: "{{ ref('stg_jira__field') }}"
    sprint: "{{ ref('stg_jira__sprint') }}"
    include_comments: true  # this package aggregates issue comments so that you have a single view of all your comments in the jira__issue_enhanced table. This can cause limit errors if you have a large dataset. Disable to remove this functionality.
    using_sprints: true # disable if you are not using sprints in Jira

models:
  jira:
    materialized: table # field history tables are configured to be incremental
    intermediate:
      materialized: ephemeral
